apiVersion: v1
kind: Secret
metadata: 
  name: aws-credentials
  data:
    accessKey: MTIzNDU2Nzg5Cg==
    secretKey: U0VDUkVUMTIzNAo=

    # echo 123456 | base64      -d mon vrai pass ! secret is not secret 
    # kubectl describe cm    kubectl describe secret