apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector:
    name: webapp
  ports: 
    - name: http
      port: 80
      nodePort: 30080

  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    name: queue
  ports: 
    - name: http
      port: 8161
      nodePort: 30010

    - name: endpoint
      port: 61616
  
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    name: position-tracker
  ports: 
    - name: http
      port: 8080

  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    name: api-gateway
  ports: 
    - name: http
      port: 8080
      nodePort: 30020

  type: NodePort
